Add: test.py and function ola to solve issue - #1
TaiBDP/Confucius-quotes pull request #2
Opened 2022-05-04 23:55 UTC by PauloGoncalvesLima

Adicionei um script para fazer o print de um parâmetro.

2022-05-04 23:56 UTC, PauloGoncalvesLima commented on teste.py
> +    ola('ooooo')
A troca para aaaaa

2022-05-04 23:57 UTC, gabrieldamotta commented on teste.py
> +    ola('ooooo')
Paulo, você trocou pra ooooo, não aaaaa

2022-05-04 23:57 UTC, 8492Diego commented on teste.py
> +    ola('ooooo')
Tô vendo seu negócio

2022-05-04 23:57 UTC, Sfregson commented on teste.py
> +    ola('ooooo')
Decepção, Paulo! Tinha que trocar para eeeee

2022-05-04 23:58 UTC, gabrieldamotta approved these changes
Top Paulo

2022-05-04 23:58 UTC, 8492Diego submitted a review, later dismissed

2022-05-04 23:58 UTC, Sfregson requested changes
Refaz tudo, está bem ruim :)

2022-05-05 00:03 UTC, 8492Diego approved these changes
Great Job Paulo!

2022-05-05 00:03 UTC, gabrieldamotta approved these changes

2022-05-05 00:05 UTC, Sfregson approved these changes
Finalmente!

2022-05-05 00:05 UTC, gabrieldamotta approved these changes

2022-05-05 00:06 UTC, Sfregson approved these changes

2022-05-05 00:07 UTC, merged